django_product/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from .sitemaps import ProductSitemap, StaticSitemap



sitemaps = {
    'product': ProductSitemap,
    'static': StaticSitemap,
}


urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path("", include("product.urls")),
    path("user/", include("users.urls")),
    path("news/", include("news.urls")),
    path("contact/", include("subscribe.urls")),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
]


handler404 = "django_product.views.handler404"
handler500 = "django_product.views.handler500"


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path("", views.NewsView.as_view(), name="news"),
    path("<slug:slug>/", views.NewsDetailView.as_view(), name="news_detail"),
]

product/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("about/", views.AboutView.as_view(), name="about"),

    path("category/", views.CategoryListView.as_view(), name="category_list"),
    path("category/<str:category>/", views.ProductView.as_view(), name="product_list"),
    path("category/<str:category>/<str:slug>/", views.ProductDetailView.as_view(), name="product_detail"),

    path('new/', views.NewProductAll.as_view(), name="all_new"),
    path('new/<slug:date>/', views.NewProductDay.as_view(), name="day_new"),

    path("add-rating/", views.add_star_rating, name='add_rating'),
    path("review/<int:pk>/", views.AddReview.as_view(), name="add_review"),
    path("search/", views.Search.as_view(), name="search"),
]

product/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.db import models
from datetime import date
from django.urls import reverse
from news.models import News
from mptt.models import MPTTModel, TreeForeignKey


class Category(MPTTModel):
    """Категории"""
    name = models.CharField(max_length=150, verbose_name="Название")
    slug = models.SlugField(max_length=250, unique=True, db_index=True, verbose_name="url")
    parent = TreeForeignKey('self', on_delete=models.CASCADE, blank=True, null=True, verbose_name="Категория",
                            related_name='children')
    poster = models.ImageField(upload_to="category/%Y/%m/%d/", verbose_name="Изображение")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("product_list", kwargs={"category": self.slug})

    class MPTTMeta:
        order_insertion_by = ['name']

    class Meta:
        unique_together = (('parent', 'slug',))
        verbose_name = 'Категория'
        verbose_name_plural = "Категории"


class Status(models.Model):
    """Статус"""
    name = models.CharField(max_length=24, verbose_name="Имя")
    draft = models.BooleanField(default=True, verbose_name="Активен")
    created = models.DateTimeField(auto_now_add=True, verbose_name="Создан")
    updated = models.DateTimeField(auto_now=True, verbose_name="Обновлен")

    def __str__(self):
        return f"{self.name}"

    class Meta:
        verbose_name = 'Статус'
        verbose_name_plural = 'Статусы'


class Product(models.Model):
    """Продукт"""
    draft = models.BooleanField(default=True, verbose_name="Показывать на сайте")
    status = models.ForeignKey(Status, null=True, blank=True, on_delete=models.SET_NULL, verbose_name="Статус")
    title = models.CharField(max_length=250, verbose_name="Название")
    slug = models.SlugField(max_length=250, unique=True, db_index=True, verbose_name="url")
    category = TreeForeignKey(Category, on_delete=models.SET_NULL, blank=True, null=True, verbose_name="Категория")
    created = models.DateField(auto_now_add=True, verbose_name="Создан")
    updated = models.DateField(auto_now=True, verbose_name="Обновлен")
    material = models.CharField(null=True, blank=True, max_length=100, verbose_name="Материал")
    country = models.CharField("Страна", null=True, blank=True, max_length=150)
    manufactures = models.CharField("Производитель", null=True, blank=True, max_length=150)
    packaging = models.CharField("Упаковка", null=True, blank=True, max_length=150)
    size = models.CharField("Размер", null=True, blank=True, max_length=150)
    quantity = models.IntegerField("В наличии", null=True, blank=True, help_text="шт.")
    retail = models.FloatField("Цена", null=True, default=0, help_text="грн.")
    sale = models.FloatField("Акция Цена", null=True, blank=True, help_text="грн.")
    persent = models.IntegerField("Скидка", null=True, blank=True, help_text="%")  # (sale / retail) -1
    description_free = models.TextField("Краткое описание", null=True, blank=True, max_length=200)
    description = RichTextUploadingField("Описание", max_length=5000)
    poster = models.ImageField("Изображение", upload_to='products/%Y/%m/%d/')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("product_detail", kwargs={"category": self.category.slug, "slug": self.slug})

    def get_review(self):
        return self.reviews_set.filter(parent__isnull=True)

    def get_rating(self):
        rating = Rating.objects.filter(product_id=self.pk)
        count = rating.count()
        sum_star = 0
        star_on = []
        star_off = []
        
        if count == 0:
            star_off = ['star_off', 'star_off', 'star_off', 'star_off', 'star_off']
            return {'star_off': star_off}
        else:
            for r in rating:
                sum_star += r.star.value
        
        star = round(sum_star / count, 1)
        
        for i in range(int(star)):
            star_on.append('star_on')

        if star - len(star_on) >= 0.5:
            star_on.append('star_on')
        
        for j in range(5 - len(star_on)):
            star_off.append('star_off')
    
        return {'star_on': star_on, 'star_off': star_off, 'star': star}


    class Meta:
        verbose_name = "Продукт"
        verbose_name_plural = "Продукты"
        ordering = ['id']

    def save(self, *args, **kwargs):
        if self.sale:
            num = (self.sale / self.retail) - 1
            self.persent = int(round(num, 2) * 100)
        else:
            self.persent = None

        super(Product, self).save(*args, **kwargs)


class ProductImage(models.Model):
    """Изображение товара"""
    title = models.CharField("Заголовок", max_length=150)
    image = models.ImageField("Изображение", upload_to='products_image/')
    product = models.ForeignKey(Product, verbose_name="Продукт", blank=True, null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Изображение товара"
        verbose_name_plural = "Изображение товаров"


class Reviews(models.Model):
    """Отзывы"""
    email = models.EmailField()
    name = models.CharField('Имя', max_length=100)
    text = models.TextField('Отзыв', max_length=5000)
    dateAdd = models.DateField("Дата добавления", default=date.today)
    parent = models.ForeignKey(
        'self', verbose_name='Родитель', on_delete=models.SET_NULL, blank=True, null=True
    )

    product = models.ForeignKey(Product, verbose_name="Товар", blank=True, null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return f"{self.name} - {self.product}"

    class Meta:
        verbose_name = "Отзыв"
        verbose_name_plural = "Отзывы"


class RatingStar(models.Model):
    """Звезда рейтинга"""
    value = models.SmallIntegerField("Значение", default=0)

    def __str__(self):
        return f'{self.value}'

    class Meta:
        verbose_name = "Звезда рейтинга"
        verbose_name_plural = "Звезды рейтинга"
        ordering = ["-value"]


class Rating(models.Model):
    """Рейтинг"""
    ip = models.CharField("IP адрес", max_length=15)
    session_key = models.CharField("Ключ сессии", max_length=128, blank=True, null=True, default=None)
    star = models.ForeignKey(RatingStar, blank=True, null=True, on_delete=models.SET_NULL, verbose_name="звезда")
    product = models.ForeignKey(Product, blank=True, null=True, on_delete=models.SET_NULL, verbose_name="товар")

    def __str__(self):
        return f"{self.star} - {self.product}"

    class Meta:
        verbose_name = "Рейтинг"
        verbose_name_plural = "Рейтинги"


class ImageHome(models.Model):
    """слайдер на главной"""
    draft = models.BooleanField("Показывать на сайте", default=True)
    title = models.CharField("Заголовок", null=True, blank=True, max_length=100)
    up_title = models.CharField("Подзаголовок", null=True, blank=True, max_length=50)
    product = models.ForeignKey(Product, verbose_name="Продукт", null=True, blank=True, on_delete=models.SET_NULL)
    news = models.ForeignKey(News, verbose_name="Новость", null=True, blank=True, on_delete=models.SET_NULL)
    slug = models.CharField("url", null=True, blank=True, max_length=250)
    btn_name = models.CharField("Текст на кнопке", null=True, blank=True, default='Подробнее', max_length=50)
    image = models.ImageField("Изображение", upload_to="slider/%Y/%m/%d/")
    
    def __str__(self):
        return f'{self.product}'

    class Meta:
        verbose_name = "Слайд"
        verbose_name_plural = "Слайды на главной"

product/forms.py
from django import forms
from .models import Reviews, RatingStar, Rating


class ReviewForm(forms.ModelForm):
    """Форма отзыва"""
    class Meta:
        model = Reviews
        fields = ("name", "email", "text")


class RatingForm(forms.ModelForm):
    """Форма добавления рейтинга"""
    star = forms.ModelChoiceField(
        queryset=RatingStar.objects.all(), 
        widget=forms.RadioSelect(), 
        empty_label=None
    )

    class Meta:
        model = Rating
        fields = ("star",)

product/views.py
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.views.generic import ListView, DetailView, TemplateView
from django.views.generic.base import View
from .models import Product, Category, Rating, ImageHome
from .forms import ReviewForm, RatingForm
from .service import get_client_ip, get_session_key, range_date
from django_product.settings import ITEM_IN_PAGE, COUNT_DAY


class IndexView(ListView):
    """главная"""
    model = ImageHome
    queryset = ImageHome.objects.filter(draft=True).order_by('-id')
    template_name = "product/index.html"


class AboutView(TemplateView):
    template_name = "product/about.html"


class CategoryListView(ListView):
    """Список категорий"""
    model = Category
    paginate_by = ITEM_IN_PAGE
    template_name = "product/category.html"
    allow_empty = False
    context_object_name = 'categories'

    def get_queryset(self):
        category = Category.objects.all()
        return category


class ProductView(ListView):
    """Список продуктов"""
    model = Product
    paginate_by = ITEM_IN_PAGE
    template_name = "product/product_list.html"
    allow_empty = True
    context_object_name = 'products'

    def get_queryset(self):
        product = Product.objects.filter(category__slug=self.kwargs['category'], draft=True)
        return product

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["category"] = Category.objects.get(slug=self.kwargs['category'])
        context["elements"] = Product.objects.filter(category__slug=self.kwargs['category'], draft=True).count()
        return context


class ProductDetailView(DetailView):
    """Полное описание продукта"""
    model = Product
    slug_field = "slug"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["star_form"] = RatingForm()
        try:
            context["rating"] = Rating.objects.get(product__slug=self.kwargs['slug'],
                                                   session_key=get_session_key(self.request)).star.value
        except:
            context["rating"] = False

        return context

    def get_queryset(self):
        product = Product.objects.filter(category__slug=self.kwargs['category'], draft=True)
        return product


class AddReview(View):
    """Отзывы"""
    def post(self, request, pk):
        form = ReviewForm(request.POST)
        print(request.POST)
        product = Product.objects.get(id=pk)
        if form.is_valid():
            form = form.save(commit=False)
            if request.POST.get("parent", None):
                form.parent_id = int(request.POST.get("parent"))
            form.product = product
            form.save()
            print(product.get_absolute_url())
        return redirect(product.get_absolute_url())


def add_star_rating(request):
    """Добавление рейтинга product"""
    form = RatingForm(request.POST)
    if form.is_valid():
        Rating.objects.update_or_create(
            ip=get_client_ip(request),
            session_key=get_session_key(request),
            product_id=int(request.POST.get("product")),
            defaults={'star_id': int(request.POST.get("star"))}
        )
    return HttpResponse(status=201)


class Search(ListView):
    """Поиск товара"""
    paginate_by = ITEM_IN_PAGE
    template_name = "product/product_search.html"
    context_object_name = 'products'

    def get_queryset(self):
        return Product.objects.filter(title__icontains=self.request.GET.get("q"))

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["q"] = f'q={self.request.GET.get("q")}&'
        context["elements"] = Product.objects.filter(title__icontains=self.request.GET.get("q")).count()
        return context


class NewProductDay(ListView):
    """вывод новинок по дате"""
    model = Product
    paginate_by = ITEM_IN_PAGE
    template_name = "product/new_product_list.html"
    allow_empty = True
    context_object_name = 'products'

    def get_queryset(self):
        product = Product.objects.filter(draft=True, created=self.kwargs['date']).order_by('-id')
        return product

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["elements"] = Product.objects.filter(draft=True, created=self.kwargs['date']).order_by('-id').count()
        context["date"] = self.kwargs['date']
        return context


class NewProductAll(ListView):
    """вывод всех новинок"""
    model = Product
    paginate_by = ITEM_IN_PAGE
    template_name = "product/new_product_list.html"
    context_object_name = 'products'

    def get_queryset(self):
        new_date = range_date()
        return Product.objects.filter(draft=True, created__range=[new_date[0], new_date[1]]).order_by('-id')

    def get_context_data(self, **kwargs):
        new_date = range_date()
        context = super().get_context_data(**kwargs)
        context["elements"] = Product.objects.filter(draft=True, created__range=[new_date[0],
                                                                                 new_date[1]]).order_by('-id').count()
        context["date"] = f'за {COUNT_DAY} дней'
        return context

templates/product/about.html
{% extends 'product/base.html' %}
{% load static %}

{% block content %}
    <!-- ::::::  Start  Main Container Section  ::::::  -->
    <main id="main-container" class="main-container">
        <div class="about-top">
            <div class="container">
                <div class="row">
                    <div class="col-md-6">
                        <div class="about-img">
                            <div class="img-responsive">
                                <img src="{% static 'image/about.jpg' %}" alt="">
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="about-content">
                            <h4 class="font--regular">Мы ориентированные на предоставление лучших игрушек и удобство для пользователей</h4>
                            <p class="para__text">"Baby toys" уже более 3 лет поставляет игрушки по всей территории Украины. Мы поставляем и продаем отличные игрушки.</p>
                            <p class="para__text">Мы производим прямые закупки товара, а также имеем прочные давние связи с ведущими производителями Украины, Китая. Ассортимент нашей компании насчитывает более 2 000 наименований игрушек. Ежемесячно мы обновляем ассортимент – самого актуального и востребованного на рынке товара.</p>
                            <p class="para__text">Оптовые клиенты для того, чтобы получить консультацию по ассортименту, обсудить условия сотрудничества, выбрать оптимальный для Вас способ доставки и сделать заказ, могут воспользоваться удобным для Вас способом связи.</p>
                            <p class="para__text">Мы внимательно следим за всеми новинками и изменениями рынка и делаем все возможное, чтобы работа с нами приносила нашим клиентам максимальные успехи в их бизнесе.</p>
                            <a href="{% url 'category_list' %}" class="btn btn--icon-left btn--small btn--radius btn--transparent btn--border-green btn--border-green-hover-green font--regular text-capitalize m-t-20">В каталог<i class="fal fa-angle-right"></i></a>
                        </div>
                    </div>
                </div>
            </div>         
        </div>
        <!-- ::::::  Start CMS Section  ::::::  -->
        <div class="cms m-t-100">
            <div class="container">
                <div class="row">
                    <!-- Start Single CMS box -->
                    <div class="col-lg-4 col-md-6 col-12">
                        <div class="cms__content">
                            <div class="cms__icon">
                                <i class="fas fa-truck"></i>
                            </div>
                            <div class="cms__text">
                                <h6 class="cms__title">Отправка новой почтой</h6>
                            </div>
                        </div>
                    </div>
                    <!-- Start Single CMS box -->
                    <div class="col-lg-4 col-md-6 col-12">
                        <div class="cms__content">
                            <div class="cms__icon">
                                <i class="far fa-money-bill-alt"></i>
                            </div>
                            <div class="cms__text">
                                <h6 class="cms__title">Наложенный платёж</h6>
                            </div>
                        </div>
                    </div>
                    <!-- Start Single CMS box -->
                    <div class="col-lg-4 col-md-6 col-12">
                        <div class="cms__content">
                            <div class="cms__icon">
                                <i class="far fa-life-ring"></i>
                            </div>
                            <div class="cms__text">
                                <h6 class="cms__title">Персональный менеджер</h6>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div> 
        <!-- ::::::  End CMS Section  ::::::  -->
    </main> 
    <!-- ::::::  End  Main Container Section  ::::::  -->
{% endblock content %}

templates/product/base.html
{% extends 'base.html' %}

{% block content %}

{% endblock content %}

templates/product/category.html
{% extends 'product/base.html' %}
{% load static %}

{% block content %}
    <!-- :::::: Start Main Container Wrapper :::::: -->
    <main id="main-container" class="main-container">
        <div class="container">
            <div class="row">
                <!-- Start Rightside - Content -->
                <div class="col-12">
                    {% include 'include/main_baner.html' %}
                    <div class="section-content" style="margin-top: 30px; margin-bottom: 30px; border-bottom: 2px solid #666;">
                        <h5 class="section-content__title">Категории</h5>
                    </div>
                    <div class="product-tab-area">
                        <div class="tab-content tab-animate-zoom">
                            <div class="tab-pane show active shop-grid" id="sort-grid">
                                <div class="row">
                                    {% for category in categories %}
                                        {% if category.slug %}
                                        <div class="col-xl-3 col-lg-4 col-md-4 col-sm-6 col-12">
                                            <!-- Start Single Default Product -->
                                            <div class="product__box product__default--single text-center">
                                                <!-- Start Product Image -->
                                                <div class="product__img-box  pos-relative">
                                                    <a href="{{category.get_absolute_url}}" class="product__img--link">
                                                        <img class="product__img img-fluid" src="{{ category.poster.url }}" alt="">
                                                    </a>
                                                </div> <!-- End Product Image -->
                                                <!-- Start Product Content -->
                                                <div class="product__content m-t-20">                                   
                                                    <a href="{{category.get_absolute_url}}" class="product__link">{{ category.name }}</a>                                               
                                                </div> <!-- End Product Content -->
                                            </div> <!-- End Single Default Product -->
                                        </div>
                                        {% endif %}
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- Start pagination -->
                    {% include "include/pagination.html" %}
                    <!-- End pagination -->
                </div>  
                <!-- Start Rightside - Content -->
            </div>
        </div>
    </main>  
    <!-- :::::: End MainContainer Wrapper :::::: -->
{% endblock content %}

templates/product/index.html
{% extends 'product/base.html' %}
{% load contact_tags %}
{% load include_tag %}
{% load static %}

{% block content %}
    <!-- :::::: Start Main Container Wrapper :::::: -->
    <main id="main-container" class="main-container">
        <!-- ::::::  Start Hero Section  ::::::  -->
        <div class="hero slider-dot-fix slider-dot slider-dot-fix slider-dot--center slider-dot-size--medium slider-dot-circle  slider-dot-style--fill slider-dot-style--fill-white-active-green dot-gap__X--10">
            {% for image in imagehome_list.all %}
            <!-- Start Single Hero Slide -->
            <div class="hero-slider">
                <img src="{{ image.image.url }}" alt="">
                <div class="hero__content">
                    <div class="container">
                        <div class="row">
                            <div class="col-12 col-lg-8">
                                <div class="hero__content--inner">
                                    {% if image.title %}
                                        <h1 class="title__hero title__hero--xlarge font--regular ">{{image.title}}</h1>
                                    {% endif %}
                                    {% if image.up_title %}
                                        <h4 class="title__hero title__hero--small font--regular">{{image.up_title}}</h4>
                                    {% endif %}
                                    {% if image.product %} 
                                        <a href="{{ image.product.get_absolute_url }}" class="btn btn--large btn--radius btn--black btn--black-hover-green font--bold text-uppercase">{{ image.btn_name }}</a>
                                    {% endif %}
                                    {% if image.news %}
                                        <a href="{{ image.news.get_absolute_url }}"  class="btn btn--large btn--radius btn--black btn--black-hover-green font--bold text-uppercase">{{ image.btn_name }}</a>
                                    {% endif %}
                                    {% if image.slug %}
                                        <a href="{{ image.slug }}"  class="btn btn--large btn--radius btn--black btn--black-hover-green font--bold text-uppercase">{{ image.btn_name }}</a>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        <!-- ::::::  Start  Product Style - Default Section  ::::::  -->
        <div class="product m-t-100">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                         <!-- Start Section Title -->
                        <div class="section-content section-content--border m-b-35">
                            <h5 class="section-content__title">Новинки</h5>
                            <a href="{% url 'all_new' %}" class="btn btn--icon-left btn--small btn--radius btn--transparent btn--border-green btn--border-green-hover-green font--regular text-capitalize">Все новинки<i class="fal fa-angle-right"></i></a>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        <div class="default-slider default-slider--hover-bg-red product-default-slider">
                            <div class="product-default-slider-4grid-1rows gap__col--30 gap__row--40">
                                {% get_last_product %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- ::::::  Start  Blog News  ::::::  -->
        <div class="blog m-t-100" style="margin-top: 110px">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <!-- Start Section Title -->
                        <div class="section-content section-content--border m-b-35">
                            <h5 class="section-content__title">Последние новости</h5>
                            <a href="{% url 'news' %}" class="btn btn--icon-left btn--small btn--radius btn--transparent btn--border-green btn--border-green-hover-green font--regular text-capitalize">Все новости <i class="fal fa-angle-right"></i></a>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        <div class="default-slider default-slider--hover-bg-red">
                            <div class="blog-feed-slider-3grid default-slider gap__col--30 ">
                                {% get_last_news %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- ::::::  Start Testimonial Section  ::::::  -->
        <div class="newsletter pos-relative">
            <div class="testimonial__bg">
                <img src="{% static 'image/review.jpg' %}" alt="">
            </div>
            <div class="testimonial__content pos-absolute absolute-center text-center" style="margin-top: -50px">
                <div class="container">
                    <div class="row">
                        <div class="col-12">
                            <div class="section-content__inner">
                                <h2>Отзывы клиентов!</h2>
                            </div>
                            <div class="testimonial__slider default-slider">
                                {% get_last_review %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- ::::::  Start Newsletter Section  ::::::  -->
        <div class="newsletter pos-relative">
            <div class="newsletter__bg">
                <img src="{% static 'image/subscribe.jpg' %}" alt="">
            </div>
            <div class="newsletter__content pos-absolute absolute-center text-center">
                <div class="container">
                    <div class="row">
                        <div class="col-12">
                            <div class="section-content__inner">
                                <h2>Email подписка</h2>
                            </div>
                        </div>
                        <div class="col-10 offset-1 col-md-8 offset-md-2 col-lg-6 offset-lg-3">
                            {% contact_form %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
    <!-- :::::: End MainContainer Wrapper :::::: -->
{% endblock content %}

templates/product/news_detail.html
{% extends 'product/base.html' %}

{% block content %}
    <main id="main-container" class="main-container">
        <!-- Start Product Details Gallery -->
        <div class="product-details m-t-100">
            <div class="container">          
                <div class="row">
                    <div class="col-md-5">                      
                        <div class="product-gallery-box product-gallery-box--default m-b-60">                          
                            <div class="product-image--large-horizontal">
                                <img style="max-width:100%;" src="{{ news.poster.url }}" alt="">
                            </div>
                        </div>
                    </div>
                    <div class="col-md-7">
                        <div class="product-details-box m-b-60">
                            <h4 class="font--regular m-b-20">{{news.title}}</h4>
                            <div class="product__desc">
                                <p style="color: #7e7e7e;">{{news.dateAdd}}</p>
                            </div>
                            <div class="font--regular m-t-5">
                                {{news.description | safe}}
                            </div>
                        </div>
                    </div>
                </div> 
            </div>
        </div>
    </main>
{% endblock content %}